### ISSUE TITLE
Improvement: Add refresh control

### ISSUE THREAD

**Issue by angelkovik** [gskbyte/GSKStretchyHeaderView#10]
Hey @gskbyte,

Thank you for the awesome work with your StretchyHeaderView, way to go! 

I have a suggestion. Is it possible to add a refresh control when pulling the table view/scroll view/collection view?

Thanks in advance,
Nikola

**Comment by gskbyte** [comment]
Hi @angelkovik ,

thanks for the appreciation :). This is already implemented, you can check the refresh control in the airbnb example view controller.

Best regards
