### ISSUE TITLE
How to set maximumContentHeight equals to NavBar+StatusBar height

### ISSUE THREAD

**Issue by fabidona** [gskbyte/GSKStretchyHeaderView#12]
Hi,
I would the header view's max height equals to (
navbar+statusbar) height. I set the maximumContentHeight to 64pt (nav+status) to test but the header height seems to fix always at 128pt.

is it a bug?

thanks

![foto-10-06-16 -08-53-32](https://cloud.githubusercontent.com/assets/5243431/15956755/f58781aa-2eea-11e6-8986-58d0af61edc2.jpg)

**Comment by fabidona** [comment]
ok, some progress...
setting maximumContentHeight to 0pt the header is showed only on top of navbar+statusbar.

Now the problem is scrolling up until the minimumContentHeight (set to 0pt): when the height is between minContentHeight and maxContentHeight the scrollview's content not scroll under the headerView. 
When the height reaches the minContentHeight the behave is correct.

My test:

```
self.headerView.minimumContentHeight  = 64.0f;
self.headerView.maxContentHeight = 0.0f;
```

**Comment by gskbyte** [comment]
Hi, I just tested one of the examples and this works, if I understood the problem well:

``` objc
self.headerView.minimumContentHeight  = 0;
self.headerView.maximumContentHeight = 64;
```

The `minimumContentHeight should` never be lower than the `maximumContentHeight`

Best regards
