### ISSUE TITLE
Carthage

### ISSUE THREAD

**Issue by benMohamed** [gskbyte/GSKStretchyHeaderView#19]
Hello,

Can you please support  Carthage?

Thanks

**Comment by gskbyte** [comment]
Hi,

thanks for opening this issue, it's actually a pretty good idea. I will try to have it ready by the end of the week.

Best regards

**Comment by benMohamed** [comment]
Nice 👍

**Comment by gskbyte** [comment]
Hey, I just added compatibility with Carthage. It required some big changes in the project, but everything seems to work well :D

Have fun!

**Comment by benMohamed** [comment]
good work
