### ISSUE TITLE
App crashes when removing GSKStretchyHeaderView from superview

### ISSUE THREAD

**Issue by tomasonik** [gskbyte/GSKStretchyHeaderView#22]
When I try to remove StretchyHeaderView from table view, app crashes. StretchyHeaderView .stopObservingScrollView function is called two times (on didMoveToSuperview and willMoveToWindow:).
Removing KVC observer that is no longer an observer makes app crashing.

**Comment by gskbyte** [comment]
I wrote a test for it and it was crashing, luckily it was easy to fix :). It will be fixed in the version 0.12.1.

 Thanks for opening this issue!
