### ISSUE TITLE
using swift GSKStretchyHeaderView with nib

### ISSUE THREAD

**Issue by violabg** [gskbyte/GSKStretchyHeaderView#24]
I'm having problems using a GSKStretchyHeaderView associated with a nib file that exposes IBOutlet property.
I'm getting this error when I try to load the nib:
`let nibViews = NSBundle.mainBundle().loadNibNamed("GSKNibStretchyHeaderView", owner: self, options: nil)

setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key backgroundImageView.`

could you see if you can reproduce it, an eventually add it to the Example project.

Thanks for this library

**Comment by violabg** [comment]
``

**Comment by gskbyte** [comment]
Well, it seems that you are loading the wrong class. You have to subclass `GSKStretchyHeaderView` and add the properties like `backgroundImageView` there. Then load the nib using the right class name. To have compile-time error checking you can do it like this:

``` swift
let className = String(YourHeaderViewClass.Type)
let nibViews = NSBundle.mainBundle().loadNibNamed(className, owner: self, options: nil)
```

Best regards

**Comment by violabg** [comment]
Thanks for the reply.

Actually i'm not loading the wrong class, this is the complete code for my class

``` swift
import UIKit

class IniziativaHeader: GSKStretchyHeaderView {

    static let kNavBar = true

    @IBOutlet weak var backgroundImageView: UIImageView!
    @IBOutlet weak var progress: RaccoltoProgress!
    @IBOutlet weak var raccoltoBox: BoxWithLabels!
    @IBOutlet weak var donatoBox: BoxWithLabels!
    @IBOutlet weak var navigationTitleLabel: UILabel!

    override func awakeFromNib() {
        super.awakeFromNib()
        self.contentView.backgroundColor = UIColor.whiteColor()
        self.expansionMode = GSKStretchyHeaderViewExpansionMode.TopOnly
        if (IniziativaHeader.kNavBar) {
            self.minimumContentHeight = 64
        } else {
            self.navigationTitleLabel.hidden = true
        }
    }

    override func didChangeStretchFactor(stretchFactor: CGFloat) {
        var alpha = CGFloatTranslateRange(stretchFactor, 0.2, 0.8, 0, 1)
        alpha = min(0, max(1, alpha))

        self.progress.alpha = alpha;
//        self.userNameLabel.alpha = alpha;

        if (IniziativaHeader.kNavBar) {
            self.backgroundImageView.alpha = alpha;

            let navTitleFactor: CGFloat = 0.4;
            var navTitleAlpha: CGFloat = 0;
            if (stretchFactor < navTitleFactor) {
                navTitleAlpha = CGFloatTranslateRange(stretchFactor, 0, navTitleFactor, 1, 0);
            }
            self.navigationTitleLabel.alpha = navTitleAlpha;
        }
    }

}
```

and here where I'm trying to use it

``` swift
override func viewDidLoad() {
        super.viewDidLoad()

        tableView.rowHeight = UITableViewAutomaticDimension
        tableView.estimatedRowHeight = 310

        let className = String(IniziativaHeader.self)
        let nibViews = NSBundle.mainBundle().loadNibNamed(className, owner: self, options: nil)
        stretchyHeaderView = nibViews.first as? IniziativaHeader
        tableView.addSubview(stretchyHeaderView!)

        if stretchyHeaderView != nil {

            if let iniziativa = dataModel.selectedIniziativa {

                let format = Format<UIImage>(name: "original")

                stretchyHeaderView!.backgroundImageView.hnk_setImageFromURL(NSURL(string: iniziativa.image)!,
                    placeholder: UIImage(named: "placeholder"),
                    format: format,
                    failure: { error in
                        print(error)
                    }, success: { image in
                        self.stretchyHeaderView!.backgroundImageView.image = image
                })

                stretchyHeaderView!.raccoltoBox.setTopLabelWithCurrency(iniziativa.raccolto)
                stretchyHeaderView!.donatoBox.setTopLabelWithCurrency(iniziativa.donato)
                stretchyHeaderView!.navigationTitleLabel.text = iniziativa.title
            }
        }
    }
```

and this is the complete error

**\* Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<reteDelDono.IniziativaViewController 0x7f90b0c6ddd0> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key backgroundImageView.'
**\* First throw call stack:
(
    0   CoreFoundation                      0x00000001068f6d85 **exceptionPreprocess + 165
    1   libobjc.A.dylib                     0x000000010636adeb objc_exception_throw + 48
    2   CoreFoundation                      0x00000001068f69c9 -[NSException raise] + 9
    3   Foundation                          0x0000000105f3519b -[NSObject(NSKeyValueCoding) setValue:forKey:] + 288
    4   UIKit                               0x0000000107748d0c -[UIViewController setValue:forKey:] + 88
    5   UIKit                               0x000000010797f7fb -[UIRuntimeOutletConnection connect] + 109
    6   CoreFoundation                      0x0000000106830890 -[NSArray makeObjectsPerformSelector:] + 224
    7   UIKit                               0x000000010797e1de -[UINib instantiateWithOwner:options:] + 1864
    8   UIKit                               0x0000000107980415 -[NSBundle(UINSBundleAdditions) loadNibNamed:owner:options:] + 223
    9   reteDelDono                         0x00000001057ab388 _TFC11reteDelDono24IniziativaViewController11viewDidLoadfT_T_ + 872
    10  reteDelDono                         0x00000001057ac6c2 _TToFC11reteDelDono24IniziativaViewController11viewDidLoadfT_T_ + 34
    11  UIKit                               0x0000000107750984 -[UIViewController loadViewIfRequired] + 1198
    12  UIKit                               0x000000010775693b -[UIViewController __viewWillAppear:] + 120
    13  UIKit                               0x0000000107786750 -[UINavigationController _startCustomTransition:] + 1203
    14  UIKit                               0x0000000107796b9b -[UINavigationController _startDeferredTransitionIfNeeded:] + 712
    15  UIKit                               0x0000000107797d0b -[UINavigationController __viewWillLayoutSubviews] + 57
    16  UIKit                               0x0000000107946503 -[UILayoutContainerView layoutSubviews] + 248
    17  UIKit                               0x0000000107670980 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 703
    18  QuartzCore                          0x000000010746cc00 -[CALayer layoutSublayers] + 146
    19  QuartzCore                          0x000000010746108e _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 366
    20  QuartzCore                          0x0000000107460f0c _ZN2CA5Layer28layout_and_display_if_neededEPNS_11TransactionE + 24
    21  QuartzCore                          0x00000001074553c9 _ZN2CA7Context18commit_transactionEPNS_11TransactionE + 277
    22  QuartzCore                          0x0000000107483086 _ZN2CA11Transaction6commitEv + 486
    23  UIKit                               0x00000001075e219b _afterCACommitHandler + 174
    24  CoreFoundation                      0x000000010681bc37 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION** + 23
    25  CoreFoundation                      0x000000010681bba7 __CFRunLoopDoObservers + 391
    26  CoreFoundation                      0x00000001068117fb __CFRunLoopRun + 1147
    27  CoreFoundation                      0x00000001068110f8 CFRunLoopRunSpecific + 488
    28  GraphicsServices                    0x000000010d612ad2 GSEventRunModal + 161
    29  UIKit                               0x00000001075b5f09 UIApplicationMain + 171
    30  reteDelDono                         0x00000001057c3a22 main + 114
    31  libdyld.dylib                       0x0000000109f4092d start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by gskbyte** [comment]
Hmm, that's weird... Did you set the correct class name in the nib file?

**Comment by violabg** [comment]
Yes I did. 
Would you mind trying to reproduce this and see if it is me or a problem?

**Comment by gskbyte** [comment]
Hi @violabg,

I'm pretty sure it's not a problem of the header view, it seems to be something related to your project configuration, or some class is not loaded correctly. I'm on vacation from tomorrow until Monday, if you haven't found a solution until then I will try to help you more.

Best regards

**Comment by violabg** [comment]
I have downloaded your project and tried to add a nib to ScalableLabelHeaderView and I got the same error.
Anyway, thanks a have a great vacation.

**Comment by violabg** [comment]
I found the problem, I was setting the class name on the first responder instead that on the view.
Sorry to bother you.

**Comment by gskbyte** [comment]
Hi @violabg,

nice to read that you solve the problem! Have fun!
