### ISSUE TITLE
Using GSKStretchyHeaderView without CocoaPod

### ISSUE THREAD

**Issue by damthieuquang** [gskbyte/GSKStretchyHeaderView#26]
Hello @gskbyte,

I having issue when I try to using your library without CocoaPod.

Can you teach me to use it?

**Comment by gskbyte** [comment]
Hi @damthieuquang ,

you have two options: you can use [Carthage](https://github.com/Carthage/Carthage) or you can just copy [all files from this folder](https://github.com/gskbyte/GSKStretchyHeaderView/tree/master/GSKStretchyHeaderView/Classes) to your project.

Best regards

**Comment by damthieuquang** [comment]
Thank @gskbyte
