### ISSUE TITLE
Header content above cells...

### ISSUE THREAD

**Issue by markst** [gskbyte/GSKStretchyHeaderView#27]
Hey, thanks for great work. 

I'm trying to achieve the following:
![image](https://cloud.githubusercontent.com/assets/274318/17782427/53712cec-656b-11e6-840c-ee4ea9e2694f.png)

We wish for the green 'share' button to float above content.
However it seems the view hierarchy doesn't allow this as the header sits below cells. 

So far only able to achieve this:
![image](https://cloud.githubusercontent.com/assets/274318/17782473/898ec30c-656b-11e6-9d9e-5790529c03b4.png)

Perhaps this is impossible & I need to add the share button as it's own subview to the table view. 
However, I wonder if you had any suggestions?

**Comment by markst** [comment]
a compromise is to design my header as:
![image](https://cloud.githubusercontent.com/assets/274318/17782628/674f9efa-656c-11e6-95f6-f0abaebdc3a5.png)

which seems to work well

**Comment by gskbyte** [comment]
Hi!

Did you try to disable `clipSubviews` on both the header and its `contentView`? That should work :)

Best regards

**Comment by markst** [comment]
@gskbyte afraid `clipSubviews` doesn't produce the desired effect
