### ISSUE TITLE
Sections on tableview

### ISSUE THREAD

**Issue by GoNinja** [gskbyte/GSKStretchyHeaderView#28]
Hi there. Great work.

Ever tried using the library, using tableview headers? I'm having trouble with it.
tableView:(UITableView *)tableView viewForHeaderInSection:(NSInteger)section

The set header seems to stays in the original tableview Y 

![aug-22-2016 12-47-39](https://cloud.githubusercontent.com/assets/2815328/17853825/cf5d20d8-6866-11e6-9e2c-2b2f75b0ced5.gif)

Any suggestion? 

Thx

**Comment by gskbyte** [comment]
Hi,

did you try the latest example in the `master` branch, or `0.12.2`? I just checked it and it's working, you could probably take it as a model for your project.

Best regards

**Comment by GoNinja** [comment]
Hi, 

Yes, I'm using the latest version from pod, if I remove the custom sections header views I don't have any problem.

**Comment by GoNinja** [comment]
My mistake, was basing my implementation in "First example (classical Frame Layout)", and should've based on visible "Visible section headers"

Thx

**Comment by gskbyte** [comment]
Allright, I'm glad it works for you now. Have fun!
