### ISSUE TITLE
How can I do auto shrink on scroll ?

### ISSUE THREAD

**Issue by bariscck** [gskbyte/GSKStretchyHeaderView#31]
Is there any way ? I would appreciate it if you could help.

**Comment by gskbyte** [comment]
I guess it should be possible, but how exactly?

**Comment by bariscck** [comment]
@gskbyte  like this 

![barisiphone](https://cloud.githubusercontent.com/assets/17647779/19524413/4d32fc98-9626-11e6-8a03-517028d38603.gif)

**Comment by gskbyte** [comment]
That GIF is displaying the reload indicator, there is an example doing exactly the same :). And if not, you can always change the `contentOffset` of the scrollView manually, and the header view will react accordingly.
