### ISSUE TITLE
Question About Collection View

### ISSUE THREAD

**Issue by axelpart** [gskbyte/GSKStretchyHeaderView#32]
Hey @gskbyte your library is really great. I am trying to use it on a swift project and i noticed something really weird. I have a collection view in which i add a custom view. My custom view contains an imageView. When i try to load an image asynchronously to the imageView nothing is happening. I mean my image view is not updated. If i initialise my image view with an image everything works properly, you can see the image. Do you have anything in your mind?

**Comment by gskbyte** [comment]
Hi Axel,

casually this week I had a similar problem at work. We had an image view to which we set the image using an AFNetworking utility method (that obviously sets the image in the main thread) but it didn't appear. However, when using the view debugger it was there. Apparently it was some weird behaviour or bug of UIKit that we solved just by playing with the `opaque` and `clipToBounds` properties.

Could you please tell me if this is also your case?

Best regards

**Comment by axelpart** [comment]
Hi Jose,

sorry for my late response. I was busy the last two weeks with my main work. More or less the problem also for me is mainly caused because i also use AFNetworking for setting the image to the image view. I tried your suggestion with the `opaque` and `clipToBounds` properties, at both image view and parent view but still no success. If you provide me with more details around your solution i can try again, otherwise you can close the issue.

Kind regards,
Alex

**Comment by gskbyte** [comment]
Hi Alex,

that's basically how we fixed it, we didn't change anything else...  Try to use `Reveal` and the integrated view debugger on Xcode to see if it helps.

Best regards
