### ISSUE TITLE
TabBarController issue

### ISSUE THREAD

**Issue by hunaid-hassan-confiz** [gskbyte/GSKStretchyHeaderView#33]
I have 3 ViewControllers inside a TabBarController and each ViewController has collectionView with StretchyHeader. Problem is every time i switch tab it adds 20px height to the header and stretch factor changes to 1.01.
It starts with stretch factor = 1 and frame height = 325, which I have set. But after I switch the tab frame height changes to 345 and stretch factor to 1.01
What could be causing this? 
If it helps, I am not using any navBar

**Comment by gskbyte** [comment]
Hi @hunaid-hassan-confiz ,

this is an interesting issue. I will try to have a look this weekend. Sorry for not answering before but I didn't have any access to my Mac :). Thanks for the detailed description!

Best regards,

Jose

**Comment by gskbyte** [comment]
Hi again,

I just updated the example project to show off how it behaves with tabs and it's working correctly without any issues. Probably you need to set `self.automaticallyAdjustsScrollViewInsets = false`.

You can see the new example here: https://github.com/gskbyte/GSKStretchyHeaderView/blob/master/Example/GSKStretchyHeaderView/TabBarViewController.swift

Good luck!

**Comment by hunaid-hassan-confiz** [comment]
Hmmm. Actually I was using a custom TransitionAnimationController. And I discovered that if I don't use that, it works fine. It must be something with how I transition the views then.
Thanks for checking up though. Cheers!
