### ISSUE TITLE
Stretchy header view only compresses if table content size big enough

### ISSUE THREAD

**Issue by kekearif** [gskbyte/GSKStretchyHeaderView#35]
Hey, I have setup a starchy header view. This header is min height 64 and max height 140. I am using it as a replacement for the navigation bar. I have noticed though that the bar will only compress to its min size if the table content view size is big enough to force it to scroll enough. So if my table only has one cell or so it's not big enough to scroll. Am I doing something wrong here?

**Comment by gskbyte** [comment]
Well, that's actually the expected behaviour, because the size of the header view depends on the `contentSize` of the scrollview it belongs to. As a workaround, you could set the `tableFooterView` to be a big transparent view if the `contentSize` is too small.

**Comment by kekearif** [comment]
Thanks for your quick reply! I'll give that a shot. Figured it was probably the expected behaviour and was using a large blank cell to fill the space. A footer view sounds like a better option though. Thanks for your help.
