### ISSUE TITLE
Using GSKStretchyHeaderView with UIViewController

### ISSUE THREAD

**Issue by ericpark** [gskbyte/GSKStretchyHeaderView#37]
Hi gskbyte,

I'm currently working on a project in swift trying to use GSKStretchyHeaderView. Instead of a tableview or collectionview, I want to use a UIViewController instead. Do you know if there is any easy way of doing this?

**Comment by gskbyte** [comment]
Hi Eric,

yes, you can just add a UIScrollView to your `viewController.view` whose `contentSize` equals the screen size, and you put the header view inside it.

Hope it helps!
