### ISSUE TITLE
NSInternalInconsistencyException when observe  contentOffset

### ISSUE THREAD

**Issue by yulichandra** [gskbyte/GSKStretchyHeaderView#42]
```
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'An instance 0x16018be00 of class ArticleDetailTableView was deallocated while key value observers were still registered with it. Current observation info: <NSKeyValueObservationInfo 0x16139d720> (
<NSKeyValueObservance 0x16139d6f0: Observer: 0x161392750, Key path: contentOffset, Options: <New: YES, Old: YES, Prior: NO> Context: 0x0, Property: 0x15fe19b40>
)'
*** First throw call stack:
(0x182342db0 0x1819a7f80 0x182342cf8 0x182c96d80 0x1819c1ae8 0x1822209fc 0x1822f6bc0 0x182220c50 0x183b08088 0x18750e088 0x10025abec 0x181dbe8b8)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

I always got this error. This happen when tableview removed from superview.

Any idea to solve this error?

**Comment by glassipbel** [comment]
Try to remove all observers from the tableview before removing the tableView.

**Comment by yulichandra** [comment]
@kbelter thanks for reply.
i try using ```- (void)willMoveToWindow:(nullable UIWindow *)newWindow``` from ```GSKStretchyHeaderView``` when my view removed.

and when dealloc i also put ```[Notification defaultCenter] removeObserver:self.tableView]```

**Comment by yulichandra** [comment]
i already solved it. my own mistakes. thanks for help.

**Comment by gskbyte** [comment]
@kbelter , @yulichandra thanks for your collaboration!
