### ISSUE TITLE
Add Animation when change maximumHeightContent?

### ISSUE THREAD

**Issue by hdphuhk** [gskbyte/GSKStretchyHeaderView#43]
Hi sir, as my issue title. Can I normally add some animation when changing maximumHeightContent?
I try to put my change height code into UIView animate block but nothing happend.
Thanks

**Comment by gskbyte** [comment]
Hi, it should be possible in theory, but you will also have to change its frame manually by scrolling down the scroll view inside the UIView animation block. `-setMaximumContentHeight:` does not change the size of the header view automatically: https://github.com/gskbyte/GSKStretchyHeaderView/blob/master/GSKStretchyHeaderView/Classes/GSKStretchyHeaderView.m#L89

**Comment by hdphuhk** [comment]
Hi, can I strech the view by code, instead by user finger? :(

**Comment by gskbyte** [comment]
Hi, I explained it in my previous comment :)
