### ISSUE TITLE
How to use Twitter Style

### ISSUE THREAD

**Issue by yatanadam** [gskbyte/GSKStretchyHeaderView#44]
Hi,

I have implemented   GSKStretchyHeaderView to my swift project by using cocoapods.

I couldn't find any information about how to  set as Twitter style header view.
Is there any information about that ?

Thanks

**Comment by tache** [comment]
best to take a look at the examples ... look in the subviews folder`GSKTwitterStretchyHeaderView`

**Comment by gskbyte** [comment]
Hi @yatanadam, there's no predefined "Twitter Style". However, as @tache says, you can have a look at the examples to see how you can achieve the same effect. Have fun!
