### ISSUE TITLE
Snap to minimum/maximum

### ISSUE THREAD

**Issue by dan-dr** [gskbyte/GSKStretchyHeaderView#45]
Hey!
Appreciate your work on this library.
I was wondering if there's a way to make the header snap to the minimum or maximum height (depending if the current stretch factor is closer to 0 or 1). I'm doing some fading of items inside but because a user can scroll a bit and make the header smaller, some text is stuck mid-fade which is weird. What I want is that as soon as the user releases the scrolling finger, the header will animate into the maximum or minimum size.

Any ideas on how can this be implemented?
Thanks!

**Comment by gskbyte** [comment]
Hi,

Well, you can not shrink the header view directly but you can listen to scroll events in the scroll view (`-willBeginDecellerating:` and `-didStopScrolling:`) and then set the `contentOffset` manually, that should do the trick. Also, there is an example demonstrating this technique.

Best regards

**Comment by dan-dr** [comment]
Cool. I'll give it a go. Can you point me to this specific example?

**Comment by gskbyte** [comment]
Hi, I can't tell you right now because I'm on vacation, but I'm pretty sure I did something like that in the example project :)

**Comment by dan-dr** [comment]
no probs. have fun and gtfo of github you're on a vacation! :)

**Comment by gskbyte** [comment]
Yo, I'm back from vacation :). Did you manage to solve the problem?

**Comment by dan-dr** [comment]
yep,
it's a little janky but good enough for me.
