### ISSUE TITLE
When the navigationBar is transparent, sliding phenomenon sectionHeader covered to government departments

### ISSUE THREAD

**Issue by lzzhoujielun** [gskbyte/GSKStretchyHeaderView#46]
![91925f56-0588-4e44-b190-3e8afc465a3c](https://cloud.githubusercontent.com/assets/7963251/23595570/d63a12f8-025d-11e7-86c8-250fe8dd87e7.png)
![Uploading WX20170306-111232.png…]()

**Comment by gskbyte** [comment]
Hi, could you give me some more details about this, some steps to reproduce it? How did you make the navigation bar transparent?

**Comment by gskbyte** [comment]
Closed due to inactivity
