### ISSUE TITLE
Sticky header with section views

### ISSUE THREAD

**Issue by emil622** [gskbyte/GSKStretchyHeaderView#49]
Does this work with table section views? I tried to use it with section headers and the section headers end scrolling when they reach the bottom of the initial sticky header frame. So the sticky header shrinks but the section headers stop scrolling once the initial bottom point is reached even after the sticky header is shrinked. I use plain table view style.

Thanks

**Comment by gskbyte** [comment]
Hi,

yes, there is an example in the source code. Please have a look at the implementation there, it might help you.

Best regards

**Comment by iosdevsx** [comment]
@gskbyte it doesn't work with -tableView:viewForHeaderInSection: method, 
only with -tableView:titleForHeaderInSection:
