### ISSUE TITLE
issue with UITableView style plain and sections

### ISSUE THREAD

**Issue by fabidona** [gskbyte/GSKStretchyHeaderView#5]
Hi,
how I use the library with a UITableView with style plain and sections?

I have a table with sections and scrolling not works properly: the first section row must follows the top anchor indeed it remains blocked in the initial position altougth table scrolling (see screenshoot).
Moreover the section row view passes in front of stretchheaderview and navigation bar.
I cant figured out if is a bug o is the standard bheavior with tableview and sections.

I have added few screens to explain better.
thank you

Startup: ok -> section in right place
https://slack-files.com/T0EV6LREK-F0R6K9SUW-60649597dd

Scrolling: top section must follows top anchor scrolling
https://slack-files.com/T0EV6LREK-F0R6FEZ7X-ff50bb9e91

Scrolling: section over stretchview/navbar
https://slack-files.com/T0EV6LREK-F0R66E2F2-483513ebed

**Comment by gskbyte** [comment]
Hi,

thanks for creating the issue! I just had a look and it happens because the tableview determines the top of the sticky section header view by using the contentInset, which is what the stretchy header is changing in the table view.

I will try to have a deeper look at it this afternoon and to be honest, I don't know if there is an easy/acceptable solution for this case, but as a workaround I would suggest you to use an UICollectionView because the headers in that case don't stick to the top.

Best regards

**Comment by gskbyte** [comment]
I just stumbled upon this: http://stackoverflow.com/a/27562794/305582

It's a hack but it might also work.

**Comment by fabidona** [comment]
thank you, I found a workaround based on your link:
- (void)scrollViewDidScroll:(UIScrollView *)scrollView {
  CGFloat sectionHeaderHeight = 50; //My Section Height
  
  if(scrollView.contentOffset.y >= -(_maximumScroll+sectionHeaderHeight) && scrollView.contentOffset.y <= -_minimumScroll) {
      scrollView.contentInset = UIEdgeInsetsMake(-scrollView.contentOffset.y, 0, 0, 0);
  }
  }

So the section header remains sticky until the scroll raise the minimum height that I want.
You can link minimumScroll and maximumScroll to stretchHeaderView properties maximumContentHeight e minimumContentHeight.

The overlap problem is still present.

**Comment by gskbyte** [comment]
Hi Fabio,

thanks for your feedback. The overlap bug can be easily solved, I hope I have time between today and tomorrow to fix it. Thanks for your report!

**Comment by fabidona** [comment]
Great! This can help us ? [http://stackoverflow.com/questions/2457663/uitableview-section-headers-drawing-above-front-subview](url)

https://slack-files.com/T0EV6LREK-F0RF1RG4Q-7b3746d3e2

**Comment by gskbyte** [comment]
Hi @fabidona, I opened a new PR for this. The exact lines are these: https://github.com/gskbyte/GSKStretchyHeaderView/pull/6/files#diff-182b1c9af8bcc3d785ea41d07bfe093bR130

**Comment by fabidona** [comment]
great! it works like a charm
thank you for support
