### ISSUE TITLE
HeaderView Cover custom cell 

### ISSUE THREAD

**Issue by RoyAnshu** [gskbyte/GSKStretchyHeaderView#51]
When i presenting the view controller the header covers the cell. And cell is hidden behind header View ...

**Comment by gskbyte** [comment]
That's not enough information...

**Comment by RoyAnshu** [comment]
Hello,
I had used UIViewController and UITableview classes. In UITableView I had Added GSKStretchyHeaderView (i.e. customize the nib file of headerView according to my use make it subclass of GSKStretchyHeaderView). Then i added the nib file in tableView as a subView.

But When i navigated to that view controller the headerView covers the cell. And cell is hidden behind header View . When i start scrolling then the cell gets normal and it not hidden then. The UI get perfect Behavior. This demo i was also performed with UITableViewController

But When i navigated to that view controller the first look is worst due to hidden cell..
Please suggest how to get normal UI

**Comment by RoyAnshu** [comment]
Thanks but finally its done ...
