### ISSUE TITLE
HeaderView not visible

### ISSUE THREAD

**Issue by domdiamond** [gskbyte/GSKStretchyHeaderView#54]
I implemented this functionality on table view. i outlet my header view and map it with GSKStretchyHeaderView and add as a subview on table view.

When we go to view controller header not visible then i scroll table view then header visible and invisible. i am using auto layout in header view.

can you tell me what is the problem?

**Comment by gskbyte** [comment]
Hi, without looking at the code I can not tell. Try to use the view debugger to see if the view is really added to your table view and check that the class is properly set in interface builder. You can also check the example for reference.

**Comment by domdiamond** [comment]
![screen shot 2017-06-07 at 7 19 47 pm](https://user-images.githubusercontent.com/2435130/26881891-7029f0f8-4bb6-11e7-9235-2c2b28d2d50a.png)
Yes it is visible but only on scroll

**Comment by domdiamond** [comment]
![simulator screen shot jun 7 2017 7 23 10 pm](https://user-images.githubusercontent.com/2435130/26882028-cc8e107c-4bb6-11e7-8861-977073753c6c.png)
![simulator screen shot jun 7 2017 7 23 23 pm](https://user-images.githubusercontent.com/2435130/26882040-d6b63b92-4bb6-11e7-809f-f0b9bd2ab5a3.png)

    @IBOutlet var itemsTbl:UITableView?
    @IBOutlet var headerLbl:UILabel?
    @IBOutlet var topImageView:UIImageView?
    @IBOutlet var shufflePlayButton:UIButton!
    @IBOutlet var headerView:GSKStretchyHeaderView!

itemsTbl?.addSubview(headerView)

**Comment by domdiamond** [comment]
all the other things working like content shrink and expand but header view not visible when i come to table view and it is only visible when i scroll

**Comment by gskbyte** [comment]
weird, it seems to be some layout issue. As I said before, try to use the view debugger or just force a layout on `viewWillAppear`

**Comment by gskbyte** [comment]
Hi, did you manage to fix your problem?

**Comment by domdiamond** [comment]
Yes it solved when i checked using view debugger. thanks for giving me clue.

**Comment by gskbyte** [comment]
You're welcome! Have fun!
