### ISSUE TITLE
Scalable image instead of scaleable text

### ISSUE THREAD

**Issue by DipyaChandniDas** [gskbyte/GSKStretchyHeaderView#55]
Hi Team,

can you make an example with scalable view/image in place of scalable text.

**Comment by gskbyte** [comment]
Hi,

you are more than welcome to create a PR with the new example :)

Thanks, best regards

**Comment by DipyaChandniDas** [comment]
Hi, I would have known about the concept, I would not have asked you. Can you make one for us?

**Comment by gskbyte** [comment]
Hi, I will try to have a look this weekend but it's kinda hard to find time, I'll keep you posted!

**Comment by DipyaChandniDas** [comment]
Thank you very much.

**Comment by gskbyte** [comment]
Hi, I just realised that you can have a look at the Twitter example, the background image is scaled when you pull down the header view. The Spotify-like example shows this behaviour as well, with a different implementation.

I hope it's useful. Best regards!
