### ISSUE TITLE
Pagination problems 

### ISSUE THREAD

**Issue by yvesbastos** [gskbyte/GSKStretchyHeaderView#57]
Hi! I've been using GSKStretchyHeaderView on a project. It works great, except when I use pagination on a tableView. As soon as the tableView loads more items/rows, the header jumps back to expanded mode. Also, when scrolling through pages, it jumps between totally contracted/expanded states. (eg. if my pagination count is 5, every 5 items it jumps).
I suppose these issues are respectively related to: 
1. tableView.reloadData() fired by the pagination, which causes the header to go back to its original state.
2. changes in the tableView's content height, which is breaking something.
Does anyone have any idea how to solve these issues?

**Comment by gskbyte** [comment]
Hi Yves,

to be honest I never tried the header view with the pagination enabled. I will try to have a look during the week (I'm really busy right now), but if you can provide some code or debug information, it would help me a lot.

Thanks for notifying the issue!

**Comment by gskbyte** [comment]
Hi again,

I couldn't resist testing it and tried enabling paging in the Airbnb-like example and it works like a charm, have you applied any other customisation? `reloadData()` doesn't seem to be called.

**Comment by yvesbastos** [comment]
Hi!
I´m using it with this lib: https://github.com/ilhasoft/isondemandtableview
The tableView in question is of type IsOnDemandTableView, which handles pagination and item increment. It does call reloadData() when it does that, maybe it has something to do with it?

**Comment by yvesbastos** [comment]
I´ve tried replacing the `reloadData()` with `insertRows` when the tableView fetches new items and adds to the tableView´s data source, but the problems persists. It does something weird, animating the header all the way to the bottom and then coming back to the top...

**Comment by gskbyte** [comment]
Have you tried to set `headerView.manageScrollViewInsets = false` before the changes start, and then enable it when the changes are over?

**Comment by yvesbastos** [comment]
Just tried it. No luck... It glitches when I´m scrolling towards the top and when a cell appears on screen. It just happens when I get to the initial items, before the pagination. It´s like the header doesn´t know the contentSize of the tableView changed, so it thinks it´s already over when I scroll for a delta equal to the initial height.

**Comment by IgorehaVel** [comment]
I have an issue with search bar and pagination. When i tap on search bar the offset changes. After search bar end editing method i try to download data with pagination and have Yves issues too.

**Comment by gskbyte** [comment]
Hi Yves,

any news on this issue?

**Comment by yvesbastos** [comment]
Hi, Jose!

Unfortunately, no. Due to deadlines, I had to move this issue to the end of my backlog. I will probably get back to it by the end of next week and will post any updates.

Let me know if you discover anything related to it before that!

Em 2 de out de 2017 14:50 -0300, Jose Alcalá Correa <notifications@github.com> escreveu:
