### ISSUE TITLE
Need Suggestion 

### ISSUE THREAD

**Issue by k-varma** [gskbyte/GSKStretchyHeaderView#58]
Team, 

Want to use UIPaginationViewController instead of UISegmentControl in "GSKTwitterStretchyHeaderView" Can we do that, Need exactly same Same Twitter Profile View now we have. How can we achieve that. Any Ideas/Suggestions.

**Comment by gskbyte** [comment]
No idea, I haven't tried it, it might work. Please let me know if you have success with it!

Kind regards
