### ISSUE TITLE
move avatar from center to top left of header

### ISSUE THREAD

**Issue by mrhaxic** [gskbyte/GSKStretchyHeaderView#59]
Hi,

I would like to thank you for this library, in second example we have avatar in the middle (centerX) what is the calculation If I want to move smoothly this avatar from the middle to top left of the header view while scrolling ..

Your support is highly appreciated

Regards

**Comment by gskbyte** [comment]
Hi,

it's very easy: you just have to define the initial and end origins for your label and then just apply an interpolation function every time the size of the header view changes (you can use the `didChangeStretchFactor()` method for that).

**Comment by mrhaxic** [comment]
Hi @gskbyte ,

I used `NSLayoutConstraint` in initial, to center the UIImageView horizontally then how could you set end origins with this method  `didChangeStretchFactor()`

Appreciating your support by example ..

Regards

**Comment by gskbyte** [comment]
Hi,

you can use the method `CGPointInterpolate` defined here: https://github.com/gskbyte/GSKStretchyHeaderView/blob/master/GSKStretchyHeaderView/Classes/GSKGeometry.h
Then just apply the factor you get in `didChangeStretchFactor()` to a [min, max] range and you will get a smooth linear movement there
