### ISSUE TITLE
Tap on headerView or tableview the header view  collapse .

### ISSUE THREAD

**Issue by akashjacob** [gskbyte/GSKStretchyHeaderView#60]
when I tap anywhere on the screen i.e. on the tableview cell or header view . the header view collapse . I want that it only collapse when I scroll the tableview or header view . please help to find the solution.

with regards 
Akash Jacob

**Comment by gskbyte** [comment]
Hello,

that shouldn't be happening, are you doing any operation on the table view after tapping the cell? Please attach a video or an example, with that information I can't say much.

Best regards

**Comment by akashjacob** [comment]
I think it may be problem with tableview , Now I replaced the tableview with collection view , it working now. So @gskbyte  thank you very much for replying.
