### ISSUE TITLE
UIRefreshControl in wrong position

### ISSUE THREAD

**Issue by DrBeak1** [gskbyte/GSKStretchyHeaderView#61]
First: Amazing control. Really encompasses a whole bunch of functionality that I needed. Thank you.

I'm having an issue where my tableView's refreshControl (1) appears behind my header view and (2) is positioned incorrectly.

1 was solved by calling bringSubviewToFront on the refreshControl. But 2 is a bit trickier. I suspect that the issue is related to the adjustment of the maximumContentHeight var, which is something that changes in my app based on the presence (or lack of) of some content. I've tried removing the refreshControl and then adding it back to the tableView after each height adjustment, but that doesn't seem to work. I'm also aware that the position of the UIRefreshControl is in alignment with the tableView's top inset; which I'm adjusting to work appropriately with the tableView section headers.

I tried searching through archived issues related to UIRefreshControl, but didn't find one that was answered properly.

https://github.com/gskbyte/GSKStretchyHeaderView/issues/18
https://github.com/gskbyte/GSKStretchyHeaderView/issues/52

If you have any ideas, I'd be grateful for any insight. Ty :)

**Comment by DrBeak1** [comment]
To get this working I had to adjust the bounds of the UIRefreshControl after each time I adjusted the maximumContentHeight. I subclassed to UIRefreshControl to make this easier, but is really unnecessary.

```
        CGPoint point = self.refreshControl.bounds.origin;
        point.y = -(self.menuHeaderView.maximumContentHeight) + 80.0;
        [self.refreshControl updateOrigin:point];
```

And subclass func `updateOrigin`:
```
-(void)updateOrigin:(CGPoint)point
{
    CGRect original = self.bounds;
    original.origin = point;
    self.bounds = original;
    
    [self beginRefreshing];
    [self endRefreshing];
}
```

**Comment by annjawn** [comment]
@DrBeak1 I was facing the same issue. Thanks for the solution. It works great.
