### ISSUE TITLE
Use it in UIScrollView

### ISSUE THREAD

**Issue by guillosaracco** [gskbyte/GSKStretchyHeaderView#7]
Is it possible to implement GSKStretchyHeaderView in a UIScrollView?

Thank you for this awesome contribution!

**Comment by gskbyte** [comment]
Yes, it should be possible although I haven't performed any experiment yet. It actually needs to be added to a `UIScrollView` or one of its subclasses to work, that's why it works for both `UICollectionView` and `UITableView`. Tell me please if it works for you, thanks!

**Comment by guillosaracco** [comment]
sounds good @gskbyte
I'll give it a try and I'll let you know how it goes!

**Comment by guillosaracco** [comment]
It works! Sorry for the late update!
