### ISSUE TITLE
When using it in Interface builder.

### ISSUE THREAD

**Issue by AnupSukumaran** [gskbyte/GSKStretchyHeaderView#72]
I am having issues when using it through interface builder. Extra space is coming in between the header and the table. when the app starts it becomes like this 

![simulator screen shot - iphone 6s - 2017-10-27 at 14 51 49](https://user-images.githubusercontent.com/32585771/32097328-ce73df36-bb26-11e7-98e8-d12b475e58d1.png)

And when I try to scroll, this happens.

![simulator screen shot - iphone 6s - 2017-10-27 at 14 50 07](https://user-images.githubusercontent.com/32585771/32097356-df079c2a-bb26-11e7-9168-683507cb9360.png)

Can you please help with this. FYI , I am using this in swift.

**Comment by gskbyte** [comment]
This looks like an issue with iOS 11, is it the case?
