### ISSUE TITLE
Xcode 9.1 App terminates when instantate GSKStretchyHeaderView through Bundle.main.loadNibNamed(...)

### ISSUE THREAD

**Issue by miserya** [gskbyte/GSKStretchyHeaderView#73]
I made subclass of GSKStretchyHeaderView and made the view of header in InterfaceBuilder.
When I call:
`Bundle.main.loadNibNamed("MyStretchyHeaderView", owner: nil, options: nil)?.first as! MyStretchyHeaderView`

application terminates at line (GSKStretchyHeaderView.m, line 48):
`NSAssert(frame.size.height > 0, @"Initial height MUST be greater than 0");`

Before Xcode update I don't have such problem.

**Comment by gskbyte** [comment]
Hi! I just tested the test project and it's working with the examples provider. That line is inside the `-initWithFrame:` method, that shouldn't be called when you load a header view from a nib. Are you sure you are setting up the view properly?
