### ISSUE TITLE
Additionnal features for GSKSpotyLikeHeaderView

### ISSUE THREAD

**Issue by Hugo75002** [gskbyte/GSKStretchyHeaderView#75]
Hello
I have finally successfully implemented your impressive Pods.
I have some questions for you pls :

1/ Change dynamically the imagename : UIImage imageNamed:@"

 I ve chosen GSKSpotyLikeHeaderView.m subview.
But I m working with Swift 4 and I need to change dynamically the image.
I ve a global variable declared in another swift class with the correct imagename.
Any idea to implement it from my ViewController in Swift ?

2/ For the blurred effect, you don’t do that with code. You just have two images one blurred the others plain. How could we do that programmatically ?
Or how do you blurred your image ?

3/ any idea, if I want apply a color.blue to my navigation bar as soon as the imageview is disappeared ?

Many thanks for your work.

**Comment by gskbyte** [comment]
Hi!

Cool that you are liking it! I would suggest you to post these questions in StackOverflow, it's a better place for that and you will get more answers and more quickly.

1) have a public image property like
```swift
var backgroundImage: UIImage? {
    get { return self.backgroundImageView.image }
    set { self.backgroundImageView.image = newValue } 
}
```

2) This example implementation is very cheap, to do it right you may use an `UIVisualEffectView`
3) Add an overlay view inside the `contentView` whose height is `minimumHeight`, set its background color to blue and interpolate its alpha using the `stretchFactor` callback, just like for the blur.

Have fun!

**Comment by Hugo75002** [comment]
I have declared the public image property as suggested in my swift class.(PresentViewController )
But i still get an error :

> Value of type 'PresentationViewController' has no member 'backgroundImageView'
