### ISSUE TITLE
the stretchy header shows the whole tableView on reloading the tableview

### ISSUE THREAD

**Issue by kareem5** [gskbyte/GSKStretchyHeaderView#77]
When I call tableview.reloadDate method, it shows the image in the full tableview's frame.
Can you please share help to fix that?

Thanks,

![img_eaf8b70fe6d4-1](https://user-images.githubusercontent.com/8720772/32829166-5122fa9a-ca02-11e7-9aa7-c182e246e88b.jpeg)
![img_eaf8b70fe6d4-2](https://user-images.githubusercontent.com/8720772/32829167-514d41a6-ca02-11e7-991f-51acad1a8fe0.jpeg)

**Comment by gskbyte** [comment]
Hi, 

I'd need some more information to have a look at this. Which iOS version are you using, any special libraries? Is it happening with the provided examples?

**Comment by kareem5** [comment]
Actually it's an expandable UITableView, we are expanding/collapsing the sections by returning 0 or the number of rows depending on the section status, if it's expanded will return number of rows else returning 0. So we are calling tableView.reloadData() method each time user is clicking in the header..

**Comment by kareem5** [comment]
it seems that the issue is happens in method [layoutContentViewIfNeeded] in GSKStretchyHeaderView.m file.
value of contentViewHeight is going to be the full tableView height.
Can you please help?

Thanks,

**Comment by gskbyte** [comment]
Hi,

sorry but I won't be able to fix this until at least mid next week because I'm on vacation. However, I would recommend you to update the table view by inserting or removing the cells you need instead of reloading data, because the user experience will be much smoother and these problems will not appear.

Best regards

**Comment by kareem5** [comment]
Hi @gskbyte ,

I've fixed it calling the "**estimatedHeightForHeaderInSection**" and **estimatedHeightForRowAtIndexPath** UITableViewDelegate methods instead of setting their properties in "**viewDidLoad**" or "**viewWillAppear**" methods.

This fixed the issue.

Thanks for your support.

Best Regards,

**Comment by gskbyte** [comment]
Awesome! Thanks for the solution!
