### ISSUE TITLE
GSKStretchyHeaderViewExpansionModeImmediate Scrolling Bug

### ISSUE THREAD

**Issue by Janglinator** [gskbyte/GSKStretchyHeaderView#80]
When we set the expansion mode to immediate and use a minimum height of 64, we observe the following bug:

[https://youtu.be/Yx7xalB4xiY](https://youtu.be/Yx7xalB4xiY)

This doesn't happen if we set it to TopOnly.

**Comment by gskbyte** [comment]
Hi,

can you please see if it works correctly on iOS 10? I won't be able to have a look at this until January, as I'm on vacation and have no laptop with me.

Best regards

**Comment by Janglinator** [comment]
It looks like it's specific to iOS 11.  An impressive guess!
