### ISSUE TITLE
Header view label

### ISSUE THREAD

**Issue by mohamedmontser** [gskbyte/GSKStretchyHeaderView#88]
need to know how the label(A twitter user) which In xib file become in header view
![screen shot 2018-03-07 at 9 38 06 pm](https://user-images.githubusercontent.com/30370903/37115054-c02a63d0-2252-11e8-96c0-3a11c575001e.png)

**Comment by gskbyte** [comment]
https://github.com/gskbyte/GSKStretchyHeaderView/blob/master/Example/GSKStretchyHeaderView/GSKTwitterStretchyHeaderView.m
