### ISSUE TITLE
Swift Support

### ISSUE THREAD

**Issue by classified** [gskbyte/GSKStretchyHeaderView#9]
How to use this library with Swift?

When i'm trying to  import GSKStretchyHeaderView it throws me error

**Comment by gskbyte** [comment]
Hi, you need to create a bridging header and write this into that file:

`@import GSKStretchyHeaderView;`

I will update the example project this week with a new example to show how it works :)

**Comment by gskbyte** [comment]
Hi @classified, as promised, an example written in Swift has been added to the example app: https://github.com/gskbyte/GSKStretchyHeaderView/commit/6b922ebb3b3cb17ce8cc15e2e9b3ede40f250473

**Comment by classified** [comment]
Thank you. That's very much helpful.

**Comment by violabg** [comment]
I can't get it to work on a swift project, I have a bridge header but doesn't work.

**Comment by enricopiovesan** [comment]
Hi @gskbyte , awesome project!
Have you added an example written in Swift?

**Comment by gskbyte** [comment]
Hi @enricopiovesan, yes, I added it, you can find it in the example project

**Comment by enricopiovesan** [comment]
@gskbyte great! Thank you!

**Comment by PriyamDutta** [comment]
Hi @gskbyte  I need to auto scroll my tableview to top after some amount of dragging to a threshold point. How can it be done because if I am setting contentOffset.y of my table view whole content is getting distorted.

**Comment by gskbyte** [comment]
Hi,

please open a new issue with more information (like screenshots, system version, etc), I can't say much with that description...

Regards

**Comment by Nitinbond** [comment]
Hello There,
          How would i implemented GSKStretchyHeaderView in swift 4.1 with storyboard. can you give me any suggestion? Please check attached screen shots, i want something like given screen shots UI.

Thanks
Nitin Kumar
![screen shot 2018-03-23 at 11 00 28 am](https://user-images.githubusercontent.com/11436995/37813111-b1550c32-2e89-11e8-9574-404edb1015db.png)
![screen shot 2018-03-23 at 11 00 17 am](https://user-images.githubusercontent.com/11436995/37813112-b17ca76a-2e89-11e8-8623-92aa2184d7dc.png)

**Comment by Nitinbond** [comment]
Please give me suggestions as soon as possible .

**Comment by fukemy** [comment]
bad library
